-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Hikom Co. Ltd. HIKVISION 30187513167",
  mode = "1920x1080@60.00",
  position = "-2000x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Display Corp. ATNA60DL01-0",
  mode = "2560x1600@240.00",
  position = "0x0",
  scale = 1.6,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
