
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Fallback for any display not named in the generated file below.
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Per-monitor layout written by hyprmoncfg (SUPER+SHIFT+M).
-- This require() is what makes the arrangement survive a restart — hyprmoncfg
-- applies changes live via hyprctl, but without loading its file here the
-- layout reverts to position="auto" on the next Hyprland start.
-- Loaded AFTER the generic rule above so its specific desc: entries win.
pcall(require, "hyprmoncfg-monitors")


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "nautilus"
local menu = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            -- Solid muted grey rather than a bright gradient: the focused
            -- window should read as edged, not outlined in light. The violet
            -- accent now lives only on the workspace dots and the launcher.
            active_border   = "rgba(979caadd)",
            inactive_border = "rgba(3c3c4566)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 6,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 6,
            passes    = 3,
            vibrancy  = 0.1696,
            noise     = 0.0117,
            contrast  = 1.0,
            brightness = 0.85,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))

-- Terminal file manager. Walks a preference list so the bind keeps working
-- whichever one is installed, and falls back to the graphical manager if none
-- are. Install the preferred one with:  sudo pacman -S yazi
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/filemanager.sh"))

-- Monitor configuration TUI (AUR: hyprmoncfg). Tells you how to get it rather
-- than failing silently if it is not installed yet.
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(
    "sh -c 'command -v hyprmoncfg >/dev/null 2>&1 && exec kitty -e hyprmoncfg || " ..
    "notify-send \"hyprmoncfg not installed\" \"Install it with: yay -S hyprmoncfg\"'"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
-- Moved off SUPER+SHIFT+S, which collided with the screenshot bind further
-- down. Hyprland keeps the first bind registered for a combo and silently
-- drops the second, so the screenshot never fired — the window just vanished
-- into the scratchpad instead.
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Keyboard equivalent of the scroll binds. SUPER + arrows is already taken by
-- directional window focus above, hence CTRL. "e+1"/"e-1" step through
-- *existing* workspaces only, so these never conjure empty ones.
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.focus({ workspace = "e-1" }))

-- Jump to the next free workspace, i.e. "new desktop". A dot appears for it
-- as soon as a window lands there.
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.focus({ workspace = "empty" }))

-- Carry the focused window to the neighbouring workspace.
hl.bind(mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + SHIFT + left",  hl.dsp.window.move({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Blur the wallpaper behind waybar so its translucent background reads as
-- glass instead of a flat black slab. ignore_alpha skips the fully clear
-- region around the bar's rounded corners, which would otherwise blur as a
-- visible rectangle.
hl.layer_rule({
    name  = "blur-waybar",
    match = { namespace = "^waybar$" },
    blur = true,
    ignore_alpha = 0.2,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
-- Nvidia
-- Video decode goes to the INTEL iGPU (iHD), not the dGPU.
--
-- Why: Hyprland advertises /dev/dri/renderD128 (pci 00:02.0, Intel) as the
-- dmabuf device to clients. With LIBVA_DRIVER_NAME=nvidia, Chromium/Brave
-- decoded on renderD129 (the 4070) and then tried to import that buffer into
-- a GL context bound to the Intel node. The cross-GPU import fails with
--   eglCreateImage failed with 0x00003009   (EGL_BAD_MATCH)
--   SharedImageManager::ProduceSkia ... CompoundImageBacking
-- and video breaks everywhere except YouTube (which falls back to software
-- decode for VP9/AV1). Decoding on the same node the compositor hands out
-- fixes it. Requires the intel-media-driver package.
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("__GLX_VENDOR_LIBRARY_NAME","nvidia")
-- NVD_BACKEND is read only by libva-nvidia-driver, which is no longer in use:
-- hl.env("NVD_BACKEND","direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT","auto")

-- AUTOSTART
hl.on("hyprland.start", function()
hl.exec_cmd("waybar")
hl.exec_cmd("hyprpaper")
-- Notification daemon. swaync is preferred because it provides a control
-- centre (the panel the clock opens); dunst has no such panel. Falls back to
-- dunst so notifications keep working if swaync is ever absent. Only one may
-- own the org.freedesktop.Notifications name, hence the either/or.
hl.exec_cmd("sh -c 'command -v swaync >/dev/null 2>&1 && exec swaync || exec dunst'")
hl.exec_cmd("wl-gammarelay-rs")
hl.exec_cmd("wl-paste --watch cliphist store")
hl.exec_cmd("hypridle")
-- nm-applet deliberately NOT started: its tray icon duplicates waybar's own
-- network module, giving two wifi indicators. Waybar covers the status, and
-- clicking it opens nm-connection-editor for the full connection UI.
-- (The command was also misspelled "nm-amplet" here, so it never ran anyway.)
-- hl.exec_cmd("nm-applet --indicator")
end)

-- Brightnes

-- Volume
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

-- Screenshot
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
-- Brightness via wl-gammarelay-rs.
-- Routed through a wrapper because the raw UpdateBrightness call does not clamp:
-- holding the key drives the value past 1.0 or below 0.0 and blacks out the panel.
-- The script clamps to 0.1-1.0 and keeps waybar's readout in sync.
local brightness = "$HOME/.config/waybar/scripts/brightness.sh"
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd(brightness .. " up"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(brightness .. " down"), { locked = true, repeating = true })


hl.env("MOZ_ENABLE_WAYLAND", "1")

-- App launcher on the Windows key alone. This is a *release* bind: SUPER_L
-- fires when the key comes back up, since a modifier held down cannot itself
-- be a press-trigger. Caveat: Hyprland also fires this when you release SUPER
-- after a combo like SUPER+Q, so the launcher can appear unbidden. Delete
-- these two lines if that becomes irritating — the bar button and SUPER+R
-- both still open it.
-- pkill -x (exact name): a bare "pkill rofi" also matches
-- power-profiles-daemon, because "rofi" is a substring of "p-rofi-les".
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("pkill -x rofi || rofi -show drun"), { release = true })

-- Blur the wallpaper behind rofi so the launcher matches the bar and terminal.
hl.layer_rule({
    name  = "blur-rofi",
    match = { namespace = "^rofi$" },
    blur = true,
    ignore_alpha = 0.2,
})

-- Same for swaync's two surfaces, otherwise whatever is underneath reads
-- straight through the translucent cards and makes the text hard to follow.
hl.layer_rule({
    name  = "blur-swaync-notifications",
    match = { namespace = "^swaync-notification-window$" },
    blur = true,
    ignore_alpha = 0.2,
})

hl.layer_rule({
    name  = "blur-swaync-control-center",
    match = { namespace = "^swaync-control-center$" },
    blur = true,
    ignore_alpha = 0.2,
})

-- Added by hyprmoncfg: its generated monitor rules load last, so nothing before this can override the applied layout.
dofile(os.getenv("HOME") .. "/.config/hypr/hyprmoncfg-monitors.lua")

-- Terminal: clear translucency instead of frosted glass. Blur stays enabled
-- globally (waybar, rofi and swaync still rely on it via their layer rules);
-- this rule opts kitty out so the wallpaper reads sharply through it.
--
-- Side effect worth knowing: decoration.blur.brightness (0.85) only applies to
-- blurred surfaces, so removing blur also removes that dimming. kitty's own
-- background_opacity is now the only thing darkening the window.
hl.window_rule({
    name  = "kitty-no-blur",
    match = { class = "^kitty$" },
    no_blur = true,
})

-------------------------------
---- IDLE / LOCK / SESSION ----
-------------------------------

-- Lid close locks the session; opening it wakes the displays. `locked = true`
-- is essential — without it the bind is ignored while the session is already
-- locked, so opening the lid would leave the screen dark.
hl.bind("switch:on:Lid Switch",  hl.dsp.exec_cmd("loginctl lock-session"),        { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.dpms(\"on\")'"), { locked = true })

-- Lock now.
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))

-- Power menu (same rofi card the waybar button opens).
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("$HOME/.config/rofi/powermenu.sh"))

-- Clipboard history. The cliphist daemon has been collecting all along; this
-- is the missing viewer. SUPER+V is already taken by float-toggle, hence SHIFT.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(
    "sh -c 'cliphist list | rofi -dmenu -p Clipboard -theme " ..
    "$HOME/.config/rofi/launcher.rasi | cliphist decode | wl-copy'"))
